### ISSUE TITLE
AEX 4.6 for pa24

### ISSUE THREAD

**Issue by achmohan** [TingyiChen/android_device_sharp_pa24#1]
I found unofficial build aex for pa24 (sharp 304sh) on tieba baidu post (https://tieba.baidu.com/p/5883777659?lp=5028&mo_device=1&is_jingpost=0&pn=0&) with your build resources. But there is some bugs found (simcard not detected and camera cannot focus). Can you fix this issue. Not much developer interesting with this device, please...

**Comment by TingyiChen** [comment]
I already sold this device...

**Comment by JerryCheng1** [comment]
Their BSP and baseband are messy, so we given them up, including all of Sharp Aquos phone (Japan).
